apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deploy
  labels:
    env: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      name: demo-template
      labels:
        env: prod
    spec:
      containers:
        - name: apache2
          image: httpd
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "0.5"
              memory: "64Mi"
            limits:
              cpu: "1"
              memory: "128Mi"
          volumeMounts:
            - mountPath: /usr/local/apache2/htdocs
              name: demo-mounts
      volumes:
        - name: demo-mounts
          persistentVolumeClaim:
            claimName: task-pv-claim
